// <auto-generated />
using System;
using De2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace De2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423130501_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("De2.Models.Entities.Prescription", b =>
                {
                    b.Property<string>("PrescriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescriptions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("De2.Models.Entities.SpecialPrescription", b =>
                {
                    b.HasBaseType("De2.Models.Entities.Prescription");

                    b.Property<string>("DoctorLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("StorageFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("SpecialPrescriptions", (string)null);
                });

            modelBuilder.Entity("De2.Models.Entities.StandardPrescription", b =>
                {
                    b.HasBaseType("De2.Models.Entities.Prescription");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("StandardPrescriptions", (string)null);
                });

            modelBuilder.Entity("De2.Models.Entities.SpecialPrescription", b =>
                {
                    b.HasOne("De2.Models.Entities.Prescription", null)
                        .WithOne()
                        .HasForeignKey("De2.Models.Entities.SpecialPrescription", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("De2.Models.Entities.StandardPrescription", b =>
                {
                    b.HasOne("De2.Models.Entities.Prescription", null)
                        .WithOne()
                        .HasForeignKey("De2.Models.Entities.StandardPrescription", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
